---

# This play require the following variable set
#   newrelic_infra_collector_url: the http URL of the newrelic Infrastructure REST API endpoint
#   newrelic_personal_api_key: "<from user config newrelic credential>"
#   policy_id: the policy id
#   application_id: The application_id of the apm service (integer)
#   metric_name: the condition name, use for display
#   metric_type: the type of the apm metric to set a condition for
#   metric_duration: the duration before starting to alert
#   metric_operator: either 'above' or 'below' to parameterize the evaluation against the threshold value
#   metric_threshold: the threshold for the condition

- name: Get existing conditions
  shell: "curl -X GET '{{ newrelic_infra_collector_url }}/v2/alerts/conditions?policy_id={{ policy_id }}' \
     -H 'Api-Key:{{ newrelic_personal_api_key }}' -H 'Auth-Type:User-Api-Key' \
     -L"
  register: existing_conditions
  delegate_to: localhost

- set_fact: 
    condition_id: "{{ existing_conditions.stdout | from_json | json_query(query) }}"
  vars:
    query: "data[?contains(where_clause, '{{ application_id }}') && contains(where_clause, '`applicationId` =') && name=='{{ metric_name }}'] | [0].id"

- debug:
    msg: "No existing condition found for {{ metric_name }}"
  when: condition_id is not defined

- name: Prepare URL for creating
  set_fact:
    curl_command: "-X POST '{{ newrelic_infra_collector_url }}/v2/alerts/conditions'"
  when: not condition_id
- name: Prepare URL for updating
  set_fact:
    curl_command: "-X PUT '{{ newrelic_infra_collector_url }}/v2/alerts/conditions/{{ condition_id }}'"
  when: condition_id

- name: create condition payload
  template:
    src: infraCondition.source.json
    dest: "{{ playbook_dir }}/infraCondition.json"
  delegate_to: localhost

- name: Create condition
  shell: "curl {{ curl_command }} \
     -H 'Api-Key:{{ newrelic_personal_api_key }}' -H 'Auth-Type:User-Api-Key' \
     -L -H 'Content-Type: application/json' \
     -d @{{ playbook_dir }}/infraCondition.json"
  delegate_to: localhost
