---

# This play require the following variable set
#   license_key: "<license_key from credential>"
# The following variables are optional
#   tags: {"dxOwningTeam":"DemoX","dxEnvironment":"development",...} JSON list of tags
#   nr_infra_collector_url: defaults to US URL if not specified
#   nr_infra_command_url: defaults to US URL if not specified
#   nr_identity_url: defaults to US URL if not specified
#   isLoggingEnabled: defaults to false if not specified. When true, will ship system logs to newrelic logging

- fail:
    msg: "license_key is required for Configuring NewRelic Infrastructure Agent"
  when: license_key is not defined

- debug:
    msg: Configuring NR Infrastructure agent

- block:
  - name: create infra config file
    template:
      src: newrelic-infra.yml
      dest: /etc/newrelic-infra.yml

  - name: Add tags header
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "  {{item.key}}: {{item.value}}"
      insertafter: 'custom_attributes:'
    loop: "{{ (tags|default({}))|dict2items }}"
    when: tags is defined

  - name: Add newrelic infra collector url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "collector_url: {{ nr_infra_collector_url }}"
      insertafter: 'license_key:'
    when: nr_infra_collector_url is defined

  - name: Add newrelic infra command url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "command_channel_url: {{ nr_infra_command_url }}"
      insertafter: 'license_key:'
    when: nr_infra_command_url is defined

  - name: Add newrelic identity url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "identity_url: {{ nr_identity_url }}"
      insertafter: 'license_key:'
    when: nr_identity_url is defined

  become: yes

- include_tasks: installLogs.yml
  when: isLoggingEnabled is defined and isLoggingEnabled == true

