---

- name: Download and Install Microsoft Visual C++ Redistributable
  win_shell: |
    (New-Object System.Net.WebClient).DownloadFile("https://aka.ms/vs/16/release/vc_redist.x64.exe", "$env:TEMP\vc_redist.x64.exe");
    start-process -FilePath "$env:TEMP\vc_redist.x64.exe" -ArgumentList "/install /q /norestart" -Verb RunAs -wait | Out-Null;

- name: Upload application event log config
  win_template:
    src: default-log.yml
    dest: "C:\\Program Files\\New Relic\\newrelic-infra\\logging.d\\logs.yml"
