---

# This play require the following variable set
#   license_key: "<license_key from credential>"
# The following variables are optional
#   tags: {"dxOwningTeam":"DemoX","dxEnvironment":"development",...} JSON list of tags
#   nr_infra_collector_url: defaults to US URL if not specified
#   nr_infra_command_url: defaults to US URL if not specified
#   nr_identity_url: defaults to US URL if not specified

- fail:
    msg: "newrelic_license_key is required for Configuring NewRelic Infrastructure Agent"
  when: newrelic_license_key is not defined

- debug:
    msg: Configuring NR Infrastructure agent

- name: Uninstall any previous agent install
  win_shell: |
    $app = Get-WmiObject -Class Win32_Product -Filter "Name = 'New Relic Infrastructure Agent'"
    $app.Uninstall()
  ignore_errors: yes

- name: Download and Install the newrelic infrastructure agent version {{ version }} with msiexec
  win_shell: |
    $LICENSE_KEY="{{ newrelic_license_key }}"; (New-Object System.Net.WebClient).DownloadFile("https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.{{ version }}.msi", "$env:TEMP\newrelic-infra.msi"); msiexec.exe /qn /i "$env:TEMP\newrelic-infra.msi" GENERATE_CONFIG=true LICENSE_KEY="$LICENSE_KEY" | Out-Null;

- include_tasks: installLogs.yml
