---

- name: Find logging.properties files
  find:
    paths: "/home/{{ remote_user }}/{{ service_id }}"
    contains: ".*java.util.logging*."
    patterns: "logging.properties"
  register: logging_found

- name: set filename fact
  set_fact:
    logging_properties_file: "{{ item['path'] }}"
  with_items: "{{ logging_found.files }}"

- name: Remove old logging properties file
  file:
    state: absent
    path: "{{ logging_properties_file }}"
  when: logging_properties_file is defined

- name: Place new logging.properties file for NR LiC
  template:
    src: logging.properties
    dest: "logging_properties_file"
  when: logging_properties_file is defined

- name: Find pom.xml file to add NR enricher dependency
  find:
    paths: "/home/{{ remote_user }}/{{ service_id }}"
    contains: ".*dependencies*."
    patterns: "pom.xml"
  register: pom_xml_found
  when: logging_properties_file is defined

- name: set filename fact
  set_fact:
    pom_xml_file: "{{ item['path'] }}"
  with_items: "{{ pom_xml_found.files }}"
  when: logging_properties_file is defined

- name: Adding NR enricher dependency to pom.xml file
  blockinfile:
    path: "{{ pom_xml_file }}"
    insertafter: ".*dependencies*."
    marker: "// {mark} NR logs enricher"
    block: |
    <dependency>
        <groupId>com.newrelic.logging</groupId>
        <artifactId>jul</artifactId>
        <version>2.0</version>
    </dependency>
  when: logging_properties_file is defined
  when: pom_xml_file is defined
