---

- name: Find src directory
  find:
    paths: "/home/{{ remote_user }}/{{ service_id }}"
    patterns: "src"
    file_type: directory
    depth: 2
    recurse: true
  register: src_found

- name: set directory fact
  set_fact:
    src_directory: "{{ item['path'] }}"
  with_items: "{{ src_found.files }}"

- name: Find logging.properties files
  find:
    paths: "{{ src_directory }}"
    contains: ".*java.util.logging*."
    patterns: "^logging\\.properties$"
    use_regex: yes
    depth: 3
    recurse: true
  register: logging_found
  when: src_found is defined

- name: set filename fact
  set_fact:
    logging_properties_file: "{{ item['path'] }}"
  with_items: "{{ logging_found.files }}"
  when: logging_found is defined

- name: Remove old logging properties file
  file:
    state: absent
    path: "{{ logging_properties_file }}"
  when: logging_properties_file is defined

- name: Place new logging.properties file for NR LiC
  template:
    src: logging.properties
    dest: "{{ logging_properties_file}}"
  when: logging_properties_file is defined

- name: Find pom.xml file to add NR enricher dependency
  find:
    paths: "/home/{{ remote_user }}/{{ service_id }}"
    contains: ".*<dependencies>*."
    patterns: "pom.xml"
  register: pom_xml_found
  when: logging_properties_file is defined

- name: set filename fact
  set_fact:
    pom_xml_file: "{{ item['path'] }}"
  with_items: "{{ pom_xml_found.files }}"
  when: logging_properties_file is defined

- name: Adding NR enricher dependency to pom.xml file
  lineinfile:
    path: "{{ pom_xml_file }}"
    insertafter: ".*<dependencies>*."
    line: "<dependency><groupId>com.newrelic.logging</groupId><artifactId>jul</artifactId><version>2.0</version></dependency>"
  when: logging_properties_file is defined and pom_xml_file is defined
